### ISSUE TITLE
As a user, I want to organize all the countries within a specific region by their population, from largest to smallest, so that I can provide valuable insights into the demographics of that region

### ISSUE THREAD

**Issue by shakad72** [shakad72/group-7-gc#3]

**Comment by shakad72** [comment]
SQL:
select Code, Name, Continent, Region, Population, (select Name from city where ID=country.capital) as Capital from country order by Population desc

No parameters needed

**Comment by MFB-Napier** [comment]
sql statement issue-3 **All the countries in a region organised by largest population to smallest**

Parameter needed 

Use world;
SELECT country.Name, country.Population
FROM country
WHERE country.region = '%region%'
ORDER BY country.Population DESC;

**Comment by shakad72** [comment]
According to the assessment document, the following fields are required for country reports:

Code, Name, Continent, Region, Population, Capital.

With that in mind, and realizing a join is required to acquire the name of the capital from the city table, the SQL query is as follows:

select country.Code , country.Name, country.Continent, country.Region, country.Population, city.Name as Capital from country inner join city on country.Capital  = city.ID 
where country.Region ='%region%';

Parameters:
%region%
