### ISSUE TITLE
As a user, I want the option to retrieve the top (N) populated countries in the world, where (N) is specified by me, so that I can gain insights into the most populous countries according to my preferences

### ISSUE THREAD

**Issue by shakad72** [shakad72/group-7-gc#4]

**Comment by MFB-Napier** [comment]
sql statement and user report issue 4 - 

report-issue4.xml
report-issue4.csv
report-issue4.html
sql-issue4.sql

Parameter needed %N% Number of countries
Use world;
SELECT country.Name, country.Population
FROM country
ORDER BY country.Population DESC
LIMIT %N%;

**Comment by MFB-Napier** [comment]
move to done

**Comment by MFB-Napier** [comment]
close

**Comment by MFB-Napier** [comment]
The issue is completed however I can´t change the status as done

**Comment by shakad72** [comment]
SQL:
select country.Code , country.Name, country.Continent, country.Region, country.Population, city.Name as Capital from country inner join city on country.Capital  = city.ID 
order by country.Population desc limit %n%;

Parameters:
%n%
