### ISSUE TITLE
As a user, I want to retrieve the top N populated countries in a specific continent, where N is specified by me, so that I can analyze the demographics and population distribution within that continent according to my preferences

### ISSUE THREAD

**Issue by shakad72** [shakad72/group-7-gc#5]

**Comment by MFB-Napier** [comment]
User report and sql statement issue 5 - The top N populated countries in a continent where N is provided by the user

src/main/resources/report-issue5.html
src/main/resources/report-issue5.csv
src/main/resources/report-issue5.xml

sql-issue5.sql
2 parameters needed:
continent - %continent%
Number of countries - %N%

Use world;

SELECT country.Name, country.Population
FROM country
WHERE country.continent = '%continent%'
ORDER BY country.Population DESC
LIMIT %N%;

**Comment by shakad72** [comment]
SQL:
select country.Code , country.Name, country.Continent, country.Region, country.Population, city.Name as Capital 
from country inner join city on country.Capital  = city.ID 
where country.Continent = '%continent%'
order by country.Population desc limit %n%;

Parameters:
%continent%
%n%
