### ISSUE TITLE
As a user, I want to retrieve the top (N) populated countries in a specific region, where (N) is specified, so that I can gain insights into the most populous countries within that region and understand the demographic trends and distributions according to my preferences

### ISSUE THREAD

**Issue by shakad72** [shakad72/group-7-gc#6]

**Comment by MFB-Napier** [comment]
Use report and sql statement issue 6 - The top N populated countries in a region where N is provided by the user.

Report files added
src/main/resources/report-issue6.csv
src/main/resources/report-issue6.html
src/main/resources/report-issue6.xml


Sql file add 

db/sql-issue1.sql

2 parameters are needed
Region %region%
Number of countries %N%

Use world;
SELECT country.Name, Country.Population
FROM country
WHERE Country.region = '%Region%'
ORDER BY Country.Population DESC
LIMIT %N%;
/db/

**Comment by shakad72** [comment]
According to the assessment document, all country reports require the following columns:

Code.
Name.
Continent.
Region.
Population.
Capital.

**Comment by shakad72** [comment]
Considering the columns required, in the order required, the SQL query will be as follows:

SELECT Code, Name, Continent, Region, Population, (select Name from city where id=country.Capital) as Capital
FROM country
WHERE region = '%region%'
ORDER BY Population DESC
LIMIT %n%;

**Comment by shakad72** [comment]
Sooo... in essence. The XML definition file should be:

<report title="The top N populated countries in a region where N is provided by the user">
    <sql>SELECT Code, Name, Continent, Region, Population, (select Name from city where id=country.Capital) as Capital FROM country WHERE region = '%region%' ORDER BY Population DESC
LIMIT %n%</sql>
    <parameters>
        <parameter name="region" prompt="Please enter the region eg. Caribbean"/>
        <parameter name="n" prompt="Please the number of rows to return (N)"/>
    </parameters>
</report>
